import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MainLayout from "../MainLayout";
import { PostsWrapper } from "../context/PostsWarpper";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ta Chi Nguyen - Blog",
  description: "Generated by create next app",
};

export default function SlugLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <MainLayout>
      <PostsWrapper>{children}</PostsWrapper>
    </MainLayout>
  );
}
